### ISSUE TITLE
Refactor sls.yml

### ISSUE THREAD

**Issue by kokakerze** [Artesius/perfsys-test#1]
You should refactor BuckeName cause it is global and it can't be deployed on our env.
s3_bucket: ${opt:s3_bucket, self:custom.app_acronym}

Error 
CREATE_FAILED: S3BucketPerfsystesttask (AWS::S3::Bucket)
Resource handler returned message: "perfsys-test-task already exists (Service: S3, Status Code: 0, Request ID: null)" (RequestToken: 0ef7f522-6913-b94e-1a7c-c3e0b7c0cc14, HandlerErrorCode: AlreadyExists)

**Comment by Artesius** [comment]
The app acronym was changed for a GitHub version for testing purposes. This should allow you to deploy it from your env

**Comment by kokakerze** [comment]
I prefer to define the buckets using the CF template in Resources (as DynamoDB) without BucketName. If you need it for further manipulations, you can use '!Ref' to get the Bucket Name and define the variable in the 'environment' or  'provider' and then add it to the resources using this variable with a link.

**Comment by Artesius** [comment]
Thanks for the recommendation! Yes, having S3 Bucket as a resource would be a comfortable upgrade. However, I think it is better to keep in one place as many customizable values as possible, so we can configure most of the app settings from custom.

**Comment by kokakerze** [comment]
The place of storing variables in the template is up to you.

**Comment by Artesius** [comment]
Added S3 Bucket resource. Added references to the newly created resource.
